import { StyleSheet, Dimensions, PixelRatio } from 'react-native';
import { RFPercentage, RFValue } from 'react-native-responsive-fontsize';
const width = Dimensions.get('screen').width;
const scale = width / 320;

export const Style = StyleSheet.create({
  flexTheme: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
  },
  background: {
    backgroundColor: '#1d243e',
  },
  textForgot: {
    color: '#b0afb2',
    fontSize: RFValue(16),
    fontFamily: 'GilroyLight',
  },
  textInput: {
    flexDirection: 'row',
    width: '100%',
    borderRadius: RFValue(55.5),
    height: RFValue(55.12),
    marginTop: RFValue(30),
    borderWidth: 1,
    borderColor: '#FFFFFF',
    alignItems: 'center',
  },
  textInputIcon: {
    width: RFValue(55.12),
    borderWidth: 1,
    borderRadius: RFValue(55.12),
    backgroundColor: 'white',
    borderColor: 'white',
    height: RFValue(55.12),
    position: 'relative',
    left: -1,
    top: -1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputInput: {
    marginRight: RFPercentage(1),
    height: RFValue(55.5),
    paddingLeft: RFValue(10),
    color: 'white',
    backgroundColor: 'transparent',
    fontSize: RFValue(16),
  },
  buttonLabel: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    marginTop: RFValue(20),
    lineHeight: RFValue(16),
  },
  button: {
    width: '100%',
    height: RFValue(55.5),
    borderRadius: RFValue(55.5),
    marginTop: RFValue(49.88),
    backgroundColor: '#1C60CD',
  },
  loginFlex: { alignItems: 'center', paddingLeft: 24, paddingRight: 24 },
  logo: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    width: 138,
    height: 144,
  },
  title: {
    fontFamily: 'GilroySemiBold',
    color: 'white',
    fontSize: RFValue(24),
    alignSelf: 'flex-start',
    lineHeight: RFValue(24),
    marginTop: RFValue(50),
    textTransform: 'uppercase',
  },
  desc: {
    fontFamily: 'GilroyLight',
    color: 'white',
    fontSize: RFValue(16),
    alignSelf: 'flex-start',
    lineHeight: RFValue(16),
    marginTop: RFValue(10),
  },
  flex: { flex: 1 },
  drawerTop: {
    flex: 0.5,
    backgroundColor: '#001F3F',
    borderBottomEndRadius: 24,
    justifyContent: 'space-between',
    paddingBottom: RFValue(37),
    paddingLeft: RFValue(49),
  },
  drawerBack: {
    width: RFValue(50),
    height: RFValue(50),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RFValue(14),
    marginTop: RFValue(70),
  },
  DrawerText: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(24),
    color: 'white',
  },
  drawerBottom: {
    flex: 1,
    marginTop: 5,
    backgroundColor: '#001F3F',
    borderTopEndRadius: 24,
  },
  pl49: { paddingLeft: RFValue(49) },
  drawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: RFValue(38),
  },
  drawerItemText: {
    fontFamily: 'GilroySemiBold',
    marginLeft: RFValue(31),
    fontSize: RFValue(14),
    lineHeight: RFValue(16),
    color: 'white',
  },
  buttonTextStyle: {
    color: 'white',
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
  },
  buttonStyle: { backgroundColor: 'transparent', width: 140 },

  rowStyle: { borderBottomColor: 'transparent', borderBottomWidth: 0 },
  dropdownStyle: {
    backgroundColor: '#083459',
    width: 155,
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 10,
  },
  renderCustomizedRowChild: { color: 'white', paddingLeft: 10 },
  logOutButton: {
    borderWidth: 1,
    borderColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '92%',
    marginLeft: '4%',
    marginRight: '4%',
  },
  logOutInner: {
    width: '55%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: '5%',
  },
  logoutText: {
    fontSize: RFValue(16),
    textTransform: 'none',
    color: 'white',
    marginTop: 0,
  },
  splitAppboxInner: { flexDirection: 'row', width: '95%' },
  splitAppbox: {
    flexDirection: 'row',
    width: '100%',
    marginTop: RFValue(30),
    maxWidth: 300,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ml10: { marginLeft: 10 },
  splitName: {
    fontFamily: 'GilroySemiBold',
    color: 'white',
    fontSize: RFValue(16),
  },
  splitSize: { color: '#505a65' },

  headerFlex: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: RFPercentage(10),
    paddingBottom: RFPercentage(3),
  },
  headerLeftButton: {
    width: RFValue(50),
    height: RFValue(50),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RFValue(14),
  },
  headerImage: { width: RFValue(106), resizeMode: 'contain', height: '100%' },
  headerText: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(20),
    color: '#FFFFFF',
    width: '100%',
  },
  headerSettingButton: {
    width: RFValue(50),
    height: RFValue(50),
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: RFValue(14),
  },
  headerHideButton: { width: RFValue(50), height: RFValue(50) },
  accountDetailsText: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
    marginBottom: RFValue(20),
  },
  settingRow: {
    marginTop: RFValue(33),
    borderColor: 'transparent',
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    borderWidth: 1,
    paddingBottom: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  settingRowTitle: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
  },
  settingRowItem: {
    fontFamily: 'GilroyLight',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
  },
  settingRowHead: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
    marginBottom: RFValue(20),
  },
  linerGrediantStyle: {
    flex: 1,
    paddingLeft: 20,
    paddingRight: 20,
  },
  locationBarfelxInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '85%',
    marginLeft: RFValue(20),
  },
  locationBarfelx: {
    marginTop: RFValue(10),
    paddingLeft: 20,
    paddingRight: 20,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 54,
    backgroundColor: '#F9F9F9',
    borderRadius: 10,
  },
  br6: { borderRadius: 6 },
  locationbartext: {
    color: '#2B2F31',
    fontSize: RFValue(14),
    lineHeight: RFValue(16),
    fontFamily: 'GilroySemiBold',
  },
  locationIconFlex: { flexDirection: 'row', alignItems: 'center' },
  searchbarFlexInput: { width: '85%', marginLeft: RFValue(20) },
  searchbarFlex: {
    paddingLeft: 20,
    paddingRight: 20,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 54,
    backgroundColor: '#F9F9F9',
    borderRadius: 10,
  },
  locationHead: {
    fontFamily: 'GilroySemiBold',
    color: '#FFFFFF',
    letterSpacing: RFValue(0.1),
    fontSize: RFValue(16),
    lineHeight: RFValue(20),
    marginTop: RFValue(20),
    marginBottom: RFValue(6),
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    position: 'relative',
    right: 80,
    paddingTop: 20,
  },
  haveanaccount: {
    fontFamily: 'GilroyLight',
    fontSize: RFValue(16),
    lineHeight: RFValue(16),
    color: '#FFFFFF',
  },
  signuptext: { fontFamily: 'GilroySemiBold', color: '#FFFFFF' },
  settingAppHead: {
    fontFamily: 'MontserratBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
    marginTop: RFValue(30),
  },
  settingAppHead1: {
    fontFamily: 'MontserratBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
  },
  settingRowTextStyle: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    color: 'white',
  },
  settingRowStyle: {
    width: '100%',
    marginTop: RFValue(33),
    borderColor: 'transparent',
    alignItems: 'center',
    borderBottomColor: 'rgba(255, 255, 255, 0.3)',
    borderWidth: 1,
    paddingBottom: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dflex: {
    flex: 1,
  },
  imageBack: {
    resizeMode: 'contain',

    height: RFValue(550),
  },
  homecontainer: {
    flex: 1,
    paddingLeft: 20,
    paddingRight: 20,
  },
  homeTop: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RFPercentage(8),
  },
  centerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: RFValue(14),
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: RFValue(14),
    width: RFValue(171),
    backgroundColor: 'rgb(52, 59, 82)',
    borderRadius: RFValue(12),
  },
  centerButtonText: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(14),
    lineHeight: RFValue(16),
    color: 'white',
    textTransform: 'uppercase',
    marginLeft: RFValue(8),
    marginRight: RFValue(8),
  },
  ipText: {
    fontFamily: 'GilroySemiBold',
    marginTop: RFValue(12),
    marginBottom: RFValue(77),
    fontSize: RFValue(16),
    lineHeight: RFValue(19),
    letterSpacing: RFValue(0.5),
    color: '#FFFFFF',
  },
  flexCenter: { justifyContent: 'center', alignItems: 'center' },
  connnectText: {
    fontFamily: 'MontserratBold',
    fontSize: RFValue(14),
    textAlign: 'center',
    lineHeight: RFValue(17),
  },
  maskedView: {
    height: 24,
    justifyContent: 'center',
    width: '100%',
  },
  buttonCenterHome: {
    height: RFValue(width / 2.8),
    width: RFValue(width / 2.8),
    borderRadius: RFValue(width / 2.8),
    backgroundColor: '#083358',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerG: {
    height: RFValue(width / 2.3),
    width: RFValue(width / 2.3),
    borderRadius: RFValue(width / 2.3),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
    left: RFValue(7),
    top: RFValue(10),
  },
  btminner: { position: 'absolute', zIndex: -1 },
  btminnerflex: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: RFValue(70),
  },
  btminner1: {
    position: 'relative',
    zIndex: 1,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: RFPercentage(10),
  },
  btmstatustext: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(14),
    lineHeight: RFValue(16),
    letterSpacing: RFValue(0.4),
    textTransform: 'uppercase',
    marginLeft: RFValue(4),
    color: '#FFFFFF',
  },
  subdownloadUploadStatus: {
    fontFamily: 'GilroyLight',
    fontSize: RFValue(12),
    lineHeight: RFValue(14),
    color: '#AAAAAA',
  },
  downloadUploadStatus: {
    fontFamily: 'GilroyLight',
    fontSize: RFValue(12),
    lineHeight: RFValue(14),
    color: '#AAAAAA',
  },
  timeText: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(28),
    lineHeight: RFValue(33),
    letterSpacing: RFValue(0.4),
    textTransform: 'uppercase',
    marginLeft: RFValue(4),
    color: '#FFFFFF',
    textAlign: 'center',
  },
  dataText: {
    fontFamily: 'GilroyLight',
    color: '#AAAAAA',
  },
  dataTextMain: {
    fontFamily: 'GilroySemiBold',
    fontSize: RFValue(14),
    lineHeight: RFValue(16),
    color: 'white',
  },
});
